name: release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: update apt
        run: apt-get update
      - name: install packages
        run: apt-get install -yq build-essential git autoconf libncurses-dev libssl-dev lsb-release
      #- name: build a deb package
      #  run: |
      #    make all
      #    sudo make build
      #- name: upload artifact
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    files: |
      #      yowcow-erlang_*.deb
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: mock artifact
        run: echo hello > test-artifact-$(lsb_release -r -s).txt
      - name: check artifact
        run: find . -type f -name 'test-artifact-*.txt'
