name: release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - ubuntu:21.10
          - ubuntu:22.04
    container:
      image: ${{ matrix.container }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: update apt
        run: apt-get update
      - name: install packages
        run: apt-get install -yq build-essential git autoconf libncurses-dev libssl-dev lsb-release
      - name: build a deb package
        run: |
          make all build
      - name: upload artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            yowcow-erlang_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
