on: [push]

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:21.10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update APT
        run: apt-get update
      - name: Install APT Packages
        run: apt-get install -yq build-essential git autoconf libncurses-dev libssl-dev lsb-release
      - name: Build a DEB Package
        run: make all build
      - name: GH Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.deb
